### ISSUE TITLE
Train.py execution error

### ISSUE THREAD

**Issue by ManzarIMalik** [microsoft/singleshotpose#106]
I am trying to train prebuilt dataset using:
`$ python train.py cfg/ape.data cfg/yolo-pose.cfg backup/ape/init.weights`
And got this error upon execution, please help in troubleshooting.

> Traceback (most recent call last):
  File "train.py", line 289, in <module>
    nsamples      = file_lines(trainlist)
  File "/content/singleshotpose/utils.py", line 1011, in file_lines
    count += buffer.count('\n')
TypeError: a bytes-like object is required, not 'str'

**Comment by nico-buehler** [comment]
I faced the same issue. Change line number 1006 to:
thefile = open(thefilepath, 'r')
