### ISSUE TITLE
Exception NameError: "global name 'FileNotFoundError' is not defined" 

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Microsoft/singleshotpose#11]
Hi, running the following command on Ubuntu 16.04:

`python train.py cfg/ape.data cfg/yolo-pose.cfg backup/ape/init.weights`

and getting:

```
/home/user/.local/lib/python2.7/site-packages/torch/cuda/__init__.py:114: UserWarning: 
    Found GPU0 TITAN V which requires CUDA_VERSION >= 9000 for
     optimal performance and fast startup time, but your PyTorch was compiled
     with CUDA_VERSION 8000. Please install the correct PyTorch binary
     using instructions from http://pytorch.org
    
  warnings.warn(incorrect_binary_warn % (d, name, 9000, CUDA_VERSION))
2018-07-11 13:05:37 epoch 0, processed 0 samples, lr 0.000100
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f5b7db5b8d0>> ignored
Traceback (most recent call last):
  File "train.py", line 399, in <module>
    niter = train(epoch)
  File "train.py", line 89, in train
    output = model(data)
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/workspace/singleshotpose/darknet.py", line 91, in forward
    x = self.models[ind](x)
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

```

Any thoughts?

**Comment by btekin** [comment]
Are you using pytorch 0.3 or 0.4? The code is based on pytorch 0.3 and there seems to be some incompatibility issues with version 0.4.

**Comment by eyildiz-ugoe** [comment]
Downgrading it to 0.3 solved the problem.
