### ISSUE TITLE
RuntimeError: invalid argument 2: size '[256 x 128 x 3 x 3]' is invalid for input with 174543 elements at ..\aten\src\TH\THStorage.cpp:84

### ISSUE THREAD

**Issue by xiaoru222** [Microsoft/singleshotpose#143]
when I triedthis "python train.py --datacfg cfg/ape.data --modelcfg cfg/yolo-pose.cfg --initweightfile cfg/darknet19_448.conv.23 --pretrain_num_epochs 15", got this error

Traceback (most recent call last):
  File "train.py", line 338, in <module>
    model.load_weights_until_last(initweightfile) 
  File "D:\singleshotpose-master\darknet.py", line 322, in load_weights_until_last
    start = load_conv_bn(buf, start, model[0], model[1])
  File "D:\singleshotpose-master\cfg.py", line 194, in load_conv_bn conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w]).view_as(conv_model.weight.data)); start = start + num_w 
RuntimeError: invalid argument 2: size '[256 x 128 x 3 x 3]' is invalid for input with 174543 elements at ..\aten\src\TH\THStorage.cpp:84

python3.7
pytorch0.41

**Comment by Choi-SeoYun** [comment]
Did you find how to solve? I got the same problem...

**Comment by SiaLight** [comment]
Did you find how to solve? I got the same problem...
