### ISSUE TITLE
IOError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Microsoft/singleshotpose#15]
I just wanted to let you know that running the following

`python valid_multi.py cfg/yolo-pose-multi.cfg backup_multi/model_backup.weights`

results with

```
Traceback (most recent call last):
  File "train_multi.py", line 408, in <module>
    niter = train(epoch)
  File "train_multi.py", line 72, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/home/user/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 188, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/user/workspace/singleshotpose/multi_obj_pose_estimation/dataset_multi.py", line 68, in __getitem__
    img, label = load_data_detection(imgpath, self.shape, jitter, hue, saturation, exposure, bgpath)
  File "/home/user/workspace/singleshotpose/multi_obj_pose_estimation/image_multi.py", line 446, in load_data_detection
    total_masked_img, label, total_mask = augment_objects(imgpath, objname, add_objs, shape, jitter, hue, saturation, exposure)
  File "/home/user/workspace/singleshotpose/multi_obj_pose_estimation/image_multi.py", line 376, in augment_objects
    img = Image.open(imgpath).convert('RGB')
  File "/home/user/.local/lib/python2.7/site-packages/PIL/Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/cvlabdata1/home/btekin/ope/yolo6D/LINEMOD/benchvise/JPEGImages/000078.jpg'
user@frankfurt:~/workspace/singleshotpose/multi_obj_pose_estimation$ gedit train_multi.py 

```

since the path is not relatively set. One may want to change this in the next release. Perhaps a setup script which sets the dataset paths would be nice.

**Comment by btekin** [comment]
This issue was resolved in #7, it was a due to a hardcoded path name, if you update the code to the most recent version, you should get rid of this error.
