### ISSUE TITLE
Errors on training provided LINEMOD data: invalid index of a 0-dim tensor

### ISSUE THREAD

**Issue by geoffhorowitz** [Microsoft/singleshotpose#154]
Having an issue training as follows:

'2021-01-27 13:29:58 epoch 0, processed 0 samples, lr 0.000100
Traceback (most recent call last):
  File "train.py", line 393, in <module>
    niter = train(epoch)
  File "train.py", line 97, in train
    loss = region_loss(output, target, epoch)
  File "/home/g/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/g/Desktop/test/singleshotpose/region_loss.py", line 134, in forward
    nProposals = int((conf > 0.25).sum().data[0])
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number'

My environment is conda as follows:
- python=3.6
- numpy
- matplotlib
- pytorch=0.4.1
- pillow
- jupyter
- pip
- pip:
    - scipy==1.2.*
    - opencv-python

didn't make any modifications to the code.  Downloaded straight from github, downloaded appropriate files + weight + etc.
anyone ever see this issue?  Any advice?  Thanks.

**Update:**
As the error describes, this was caused by the zero indexing of `data[0]`.  after .sum(), this is a single element, so this is basically saying we can't take an index of a single element.  once I removed the zero index here to `nProposals = int((conf > 0.25).sum().data)`, this worked correctly. (note, I had to make a similar adjustment to the print statement at the end of the file)

**New question**: Is this something specific about my setup?  Or are other people seeing a similar issue?  Thanks.

**Comment by Merwanski** [comment]
Hey @geoffhorowitz 
I had same issue so I don't think it is specific to your setup (tried it on Windows 10 and Ubuntu 18.04)

**Comment by MohamedKari** [comment]
Hi Geoff, 

we got the same error message. For us, the problem was that we unintentionally had updated the torch version. With torch==0.4.1, we got rid of the error message. 

Best, Mo

CC: https://github.com/luisfalconeri https://github.com/hans24o

**Comment by yueqin-li** [comment]
Hi, I got the same issue and I found two solutions online:
1) you may need to downgrade your pytorch version.
2)change 'data[0]' to 'item()' where cause problems in the code.
