### ISSUE TITLE
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'other'

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Microsoft/singleshotpose#18]
Hi,

I am trying to run the multi-obj-pose-estimation, and I do have the latest code, yet I face the following:

```
user@user:~/workspace/singleshotpose/multi_obj_pose_estimation$ python valid_multi.py cfg/yolo-pose-multi.cfg backup_multi/model_backup.weights
2018-07-12 15:13:26 Testing ape...
Traceback (most recent call last):
  File "valid_multi.py", line 170, in <module>
    valid(datacfg, cfgfile, weightfile, conf_th)
  File "valid_multi.py", line 126, in valid
    iou           = bbox_iou(bb2d_gt, bb2d_pr)
  File "/home/user/workspace/singleshotpose/utils.py", line 159, in bbox_iou
    mx = min(box1[0]-box1[2]/2.0, box2[0]-box2[2]/2.0)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'other'

```
In case if the any of the below parameters matter, here are some:

OS: Ubuntu 16.04
GPU: NVidia GTX 1060ti 6GB
Batch Size: 8

**Comment by eyildiz-ugoe** [comment]
Fixed with the last bug fix.
