### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/cvlabdata1/home/btekin/ope/yolo6D/LINEMOD/benchvise/JPEGImages/000493.jpg'

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#20]
Hi, when I try to train the multi_obj model (python train_multi.py cfg/occlusion.data cfg/yolo-pose-multi.cfg backup_multi/init.weights) i get the following error. could you please help me? Thanks

2018-07-16 15:10:06 epoch 0, processed 0 samples, lr 0.000100
Traceback (most recent call last):
  File "train_multi.py", line 408, in <module>
    niter = train(epoch)
  File "train_multi.py", line 72, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data1/edison/singleshotpose/multi_obj_pose_estimation/dataset_multi.py", line 68, in __getitem__
    img, label = load_data_detection(imgpath, self.shape, jitter, hue, saturation, exposure, bgpath)
  File "/data1/edison/singleshotpose/multi_obj_pose_estimation/image_multi.py", line 446, in load_data_detection
    total_masked_img, label, total_mask = augment_objects(imgpath, objname, add_objs, shape, jitter, hue, saturation, exposure)
  File "/data1/edison/singleshotpose/multi_obj_pose_estimation/image_multi.py", line 376, in augment_objects
    img = Image.open(imgpath).convert('RGB')
  File "/home/edison/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/cvlabdata1/home/btekin/ope/yolo6D/LINEMOD/benchvise/JPEGImages/000493.jpg'

**Comment by btekin** [comment]
This issue was resolved in #7 and also mentioned in #15, if you update the code to the most recent version and place the data folders in the indicated positions in the main directory, you should not get this error.
