### ISSUE TITLE
RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#3]
Thank you very much for your previous help, I have change all the directories for objects in 'cfg' file. by the way , i did not find "phone" file in LINEMOD dataset file you provided. now i try to train the network again ( python train.py cfg/ape.data cfg/yolo-pose.cfg /data1/edison/realtime_seamless_6D_data_and_model/dataset/backup/ape/init.weights) it shows the error below, could you please give me a help?

Traceback (most recent call last):
File "train.py", line 336, in 
model.load_weights_until_last(weightfile)
File "/home/edison/realtime_seamless_yolo_6D/singleshotpose/darknet.py", line 315, in load_weights_until_last
start = load_conv_bn(buf, start, model[0], model[1])
File "/home/edison/realtime_seamless_yolo_6D/singleshotpose/cfg.py", line 175, in load_conv_bn
conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3

**Comment by edisonchensy** [comment]
by the way, my environment : python 2.7.14 , cuda8.0, cudnn 5.1,  pytorch 0.4.0

**Comment by edisonchensy** [comment]
i have solve this problem by changing conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
->conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w]).view(conv_model.weight.data.shape)); start = start + num_w

**Comment by edisonchensy** [comment]
i have solve this problem by changing conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w


conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w]).view(conv_model.weight.data.shape)); start = start + num_w

**Comment by edisonchensy** [comment]
However, I get a new problem.

edison@amax2:~/realtime_seamless_yolo_6D/singleshotpose$ python train.py cfg/ape.data cfg/yolo-pose.cfg /data1/edison/realtime_seamless_6D_data_and_model/dataset/backup/ape/init.weights
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32
    1 max          2 x 2 / 2   416 x 416 x  32   ->   208 x 208 x  32
    2 conv     64  3 x 3 / 1   208 x 208 x  32   ->   208 x 208 x  64
    3 max          2 x 2 / 2   208 x 208 x  64   ->   104 x 104 x  64
    4 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    5 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64
    6 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    7 max          2 x 2 / 2   104 x 104 x 128   ->    52 x  52 x 128
    8 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
    9 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128
   10 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
   11 max          2 x 2 / 2    52 x  52 x 256   ->    26 x  26 x 256
   12 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   13 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   14 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   15 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   16 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   17 max          2 x 2 / 2    26 x  26 x 512   ->    13 x  13 x 512
   18 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   19 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   20 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   21 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   22 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   23 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   24 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   25 route  16
   26 conv     64  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x  64
   27 reorg              / 2    26 x  26 x  64   ->    13 x  13 x 256
   28 route  27 24
   29 conv   1024  3 x 3 / 1    13 x  13 x1280   ->    13 x  13 x1024
   30 conv     20  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x  20
   31 detection
2018-07-06 14:13:58 epoch 0, processed 0 samples, lr 0.000100
Traceback (most recent call last):
  File "train.py", line 396, in <module>
    niter = train(epoch)
  File "train.py", line 70, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/edison/realtime_seamless_yolo_6D/singleshotpose/dataset.py", line 75, in __getitem__
    img, label = load_data_detection(imgpath, self.shape, jitter, hue, saturation, exposure, bgpath)
  File "/home/edison/realtime_seamless_yolo_6D/singleshotpose/image.py", line 175, in load_data_detection
    img = Image.open(imgpath).convert('RGB')
  File "/home/edison/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'LINEMOD/ape/JPEGImages/001051.jpg'


can you please help me?

**Comment by btekin** [comment]
Thanks for pointing out the initial issue and finding a solution for this. The code is based on pytorch 0.3, that is the only difference from your setup. About the second error that you are getting: This again seems to be related to a wrong data path. If you place the dataset folder within the main code folder, you should be able to run the code without any modifications. But if the dataset is in another folder, which seems to be the case here, you should adjust the paths accordingly. I think, in this case, you should change the path names in LINEMOD/[OBJ_NAME]/train.txt, LINEMOD/[OBJ_NAME]/test.txt, etc.
