### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#47]
Hi, Mr. Tekin @btekin 
Thanks to your previous help, I have prepared all the data for my own object's training (jpeg images, labels, train.txt, test.txt, mesh .ply) However, I got this error that says I do not have mask for my object and I did not even create a mask file. Your explanation said mask is optional. So, How do I resolve this error?
please help me, thank you

Best wishes

![image](https://user-images.githubusercontent.com/32606635/46586236-162d7c00-caae-11e8-86c8-10f15a8b80f4.png)

edison@amax2:/data1/edison/singleshotpose$ python train.py cfg/wangwang.data cfg/yolo-pose-pre.cfg cfg/darknet19_448.conv.23

2018-10-08 03:39:03 epoch 0, processed 0 samples, lr 0.000100
Traceback (most recent call last):
  File "train.py", line 411, in <module>
    niter = train(epoch)
  File "train.py", line 70, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data1/edison/singleshotpose/dataset.py", line 75, in __getitem__
    img, label = load_data_detection(imgpath, self.shape, jitter, hue, saturation, exposure, bgpath)
  File "/data1/edison/singleshotpose/image.py", line 176, in load_data_detection
    mask = Image.open(maskpath).convert('RGB')
  File "/home/edison/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/data1/edison/singleshotpose/chen_lab_data/wangwang/mask/0008.png'

**Comment by edisonchensy** [comment]
By the way, because I did not create a mask file, how come it says 
IOError: [Errno 2] No such file or directory: '/data1/edison/singleshotpose/chen_lab_data/wangwang/mask/0008.png'

I am confused

**Comment by btekin** [comment]
You just have to remove or comment out the following lines in image.py to disable changing the background of your images.

https://github.com/Microsoft/singleshotpose/blob/master/image.py#L176

https://github.com/Microsoft/singleshotpose/blob/master/image.py#L179

**Comment by edisonchensy** [comment]
Thank you
