### ISSUE TITLE
AttributeError: 'str' object has no attribute 'read'

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#48]
edison@amax2:~/data1_edison/singleshotpose$ python train.py cfg/wangwang.data cfg/yolo-pose-pre.cfg cfg/darknet19_448.conv.23

2018-10-08 14:44:10 epoch 0, processed 0 samples, lr 0.000100
Traceback (most recent call last):
  File "train.py", line 411, in <module>
    niter = train(epoch)
  File "train.py", line 70, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data1/edison/singleshotpose/dataset.py", line 75, in __getitem__
    img, label = load_data_detection(imgpath, self.shape, jitter, hue, saturation, exposure, bgpath)
  File "/data1/edison/singleshotpose/image.py", line 178, in load_data_detection
    img = Image.open(imgpath).convert('RGB')
  File "/home/edison/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2549, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'str' object has no attribute 'read'
![image](https://user-images.githubusercontent.com/32606635/46599514-224f2300-cb1a-11e8-8e4e-a7064843052c.png)

Can you please help me? Thank you

**Comment by edisonchensy** [comment]
Since you said mask is optional, I create a mask file and put black images in the mask file. Now, I am running the train,py again. i get this error

**Comment by btekin** [comment]
You are most probably trying to read an empty line. Check your train.txt and test.txt if there is any empty line. Also print `imgpath` to see which path you are getting the error.

**Comment by edisonchensy** [comment]
Thank you

**Comment by nadiaphi** [comment]
> trying

How to solve empty line?
