### ISSUE TITLE
NameError: global name 'accious' is not defined

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#6]
After i trained the model i get the following result and the error, can you please help me? Thanks

2018-07-09 17:19:38    Mean corner error is 7.615080
2018-07-09 17:19:38    Acc using 5 px 2D Projection = 68.57%
2018-07-09 17:19:38    Acc using 0.0103 vx 3D Transformation = 6.48%
2018-07-09 17:19:38    Acc using 5 cm 5 degree metric = 9.62%

Traceback (most recent call last):
  File "train.py", line 400, in <module>
    test(epoch, niter)
  File "train.py", line 268, in test
    logging('   Acc using iou metric = {:.2f}%'.format(accious))
NameError: global name 'accious' is not defined

**Comment by btekin** [comment]
This was due to a stray variable ("accious"), now it should have been fixed.
