### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/cvlabdata1/home/btekin/ope/yolo6D/LINEMOD/benchvise/JPEGImages/000627.jpg'

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#7]
when I try to do Multi-object pose estimation on the OCCLUSION dataset, I train the model (python train_multi.py cfg/occlusion.data cfg/yolo-pose-multi.cfg backup_multi/init.weights)

i get this error, could you please help me? thank you. I have put dataset into code file.

Traceback (most recent call last):
  File "train_multi.py", line 408, in <module>
    niter = train(epoch)
  File "train_multi.py", line 72, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data1/edison/singleshotpose/multi_obj_pose_estimation/dataset_multi.py", line 68, in __getitem__
    img, label = load_data_detection(imgpath, self.shape, jitter, hue, saturation, exposure, bgpath)
  File "/data1/edison/singleshotpose/multi_obj_pose_estimation/image_multi.py", line 446, in load_data_detection
    total_masked_img, label, total_mask = augment_objects(imgpath, objname, add_objs, shape, jitter, hue, saturation, exposure)
  File "/data1/edison/singleshotpose/multi_obj_pose_estimation/image_multi.py", line 376, in augment_objects
    img = Image.open(imgpath).convert('RGB')
  File "/home/edison/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/cvlabdata1/home/btekin/ope/yolo6D/LINEMOD/benchvise/JPEGImages/000627.jpg'

**Comment by btekin** [comment]
I have updated the code to fix this issue, it was due to a hardcoded path name. If you now put the dataset in the code folder, you should be able to run the code.
