### ISSUE TITLE
UnboundLocalError: local variable 'add_objs' referenced before assignment

### ISSUE THREAD

**Issue by SonOfCoding** [Microsoft/singleshotpose#87]
I try to train my own objects (cookie and coke). I have followed instruction and prepared .jpg images, labels and mesh models. However, when I run the  python train_multi.py cfg/occlusion_MyOwn.data cfg/yolo-pose-multi-pre.cfg cfg/darknet19_448.conv.23. It says

Traceback (most recent call last):
  File "train_multi.py", line 419, in <module>
    niter = train(epoch)
  File "train_multi.py", line 72, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
UnboundLocalError: Traceback (most recent call last):
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data1/edison/singleshotpose/multi_obj_pose_estimation/dataset_multi.py", line 68, in __getitem__
    img, label = load_data_detection(imgpath, self.shape, jitter, hue, saturation, exposure, bgpath)
  File "/data1/edison/singleshotpose/multi_obj_pose_estimation/image_multi.py", line 443, in load_data_detection
    add_objs = get_add_objs(objname)
  File "/data1/edison/singleshotpose/multi_obj_pose_estimation/image_multi.py", line 50, in get_add_objs
    return add_objs
UnboundLocalError: local variable 'add_objs' referenced before assignment
Could you please give me a help? Thank you

I have changed part of the image_multi.py  like bleow:
def get_add_objs(objname):
    # Decide how many additional objects you will augment and what will be the other types of objects

    if objname == 'cookie':
        add_objs = ['coke']
    elif objname == 'coke':
        add_objs =['cookie']
    return add_objs

**Comment by joefriel** [comment]
The error message indicates that the value you passed to 'get_add_objs' (in objname) did not match either 'cookie' or 'coke', so when the function attempted to return a value for 'add_objs' (in the final line of code), it threw an error because add_objs had not been assigned.  Check what you are passing in to the 'get_add_objs' function.  (Also, it looks like your coke/cookie assignments are reversed).

If you are just starting on singleshotpose with your own objects, you might find it easier to use single object pose estimation (instead of multi object) at first.  Good luck.

**Comment by SonOfCoding** [comment]
thank you
