### ISSUE TITLE
 Python 3 and Pytorch 0.4 compatible version,Type error

### ISSUE THREAD

**Issue by G-YY** [microsoft/singleshotpose#94]
I test the  version that is Python 3 and Pytorch 0.4 compatible,but have met the following error:
 2019-06-08 16:03:42 Testing ape...
Traceback (most recent call last):
  File "valid_multi.py", line 170, in <module>
    valid(datacfg, cfgfile, weightfile, conf_th)
  File "valid_multi.py", line 78, in valid
    for batch_idx, (data, target) in enumerate(test_loader):
  File "/home/lab/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/lab/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/lab/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lab/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lab/singleshot6Dpose/multi_obj_pose_estimation/dataset_multi.py", line 79, in __getitem__
    tmp = torch.from_numpy(read_truths_args(labpath, 8.0/ow))
TypeError: read_truths_args() takes 1 positional argument but 2 were given

My env:torch 0.4,python 3.5 ,GPU 2080ti ,cuda 10

**Comment by shiqingshina** [comment]
Hi, i wanna know how to solve this problem. i met it too.
Thanks for your help!

**Comment by AkmaralMoldagalieva** [comment]
Hi!

I have the same problem, could you share the solution with us please. Thanks

**Comment by shiqingshina** [comment]
i solved this. 
feel free to make some change on the code. 
here is my change:
in dataset_multi.py line 79
                # tmp = torch.from_numpy(read_truths_args(labpath, 8.0/ow))
                tmp = torch.from_numpy(read_truths_args(labpath))
AND in utils.py, you could find the function read_truths_args() takes only the labpath parameter

**Comment by AkmaralMoldagalieva** [comment]
Thank you! 

I will try it today.
